### ISSUE TITLE
Clearing the text input on the google search input drawer on mobile causes the input to be unclickable

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#515] opened 2024-03-01 00:29 UTC
Steps to reproduce:

- Using an iphone, open the email your congressperson flow
- click the address, enter and select an address
- reopen the address and clear the selected address, try and select the input to retype in a new one

**Comment by kl-cb** [comment] 2024-03-13 16:41
Closing since I can't reproduce the issue anymore

**Closed** 2024-03-13 16:41 UTC
