### ISSUE TITLE
issue loading NFT mint flow

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#816] opened 2024-05-03 12:54 UTC

**Comment by travisbloom-cb** [comment] 2024-05-03 12:56
https://github.com/Stand-With-Crypto/swc-web/assets/153657370/9e84ece6-c2a3-464b-aa6f-c840d46947e1

**Comment by lucasrmp-cb** [comment] 2024-05-03 14:57
Seems like this problem is not reproducible. One theory is that it is just a thirdweb instability, hard to validate. Closing because of that

**Closed by lucasrmp-cb** 2024-05-03 14:57 UTC
